# Generated by Django 6.0 on 2025-12-22 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentpatientmedication',
            options={'ordering': ['-prescribed_at'], 'verbose_name': 'Dependent Patient Medication', 'verbose_name_plural': 'Dependent Patient Medications'},
        ),
        migrations.AlterModelOptions(
            name='patientmedication',
            options={'ordering': ['-prescribed_at'], 'verbose_name': 'Patient Medication', 'verbose_name_plural': 'Patient Medications'},
        ),
        migrations.AddField(
            model_name='dependentpatientmedication',
            name='prescribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='prescribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
