# Generated by Django 6.0 on 2025-12-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientallergy',
            name='dependent_patient',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='dependent_patient',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='dependent_patient',
        ),
        migrations.CreateModel(
            name='DependentPatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.CharField(max_length=255)),
                ('dependent_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='website.dependentpatient')),
            ],
            options={
                'verbose_name': 'Dependent Patient Allergy',
                'verbose_name_plural': 'Dependent Patient Allergies',
                'ordering': ['allergy_name'],
            },
        ),
        migrations.CreateModel(
            name='DependentPatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('dependent_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='website.dependentpatient')),
            ],
            options={
                'verbose_name': 'Dependent Patient Medication',
                'verbose_name_plural': 'Dependent Patient Medications',
                'ordering': ['medication_name'],
            },
        ),
        migrations.CreateModel(
            name='DependentPatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('dependent_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='website.dependentpatient')),
            ],
            options={
                'verbose_name': 'Dependent Patient Vital',
                'verbose_name_plural': 'Dependent Patient Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
