# Generated by Django 6.0 on 2025-12-22 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_dependentpatientmedication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_medication', models.BooleanField(default=False)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='website.medicalrecord')),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
    ]
