# Generated by Django 6.0 on 2025-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_doctorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the doctor', null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='qualifications',
            field=models.TextField(blank=True, help_text="Doctor's qualifications, e.g., MD, PhD, certifications", null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Number of years of medical experience'),
        ),
    ]
