# Generated by Django 6.0 on 2025-12-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_doctorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/profiles/'),
        ),
    ]
