# Generated by Django 6.0 on 2025-12-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_doctorinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='website.specialization'),
        ),
    ]
