# Generated by Django 6.0 on 2025-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_doctorinfo_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
