# Generated by Django 6.0 on 2025-12-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_doctorinfo_approved_at_doctorinfo_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
