# Generated by Django 6.0 on 2025-12-23 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentpatientallergy',
            options={'ordering': ['allergy_name'], 'verbose_name_plural': 'Dependent Patient Allergies'},
        ),
        migrations.AlterModelOptions(
            name='dependentpatientvitals',
            options={'ordering': ['-recorded_at'], 'verbose_name_plural': 'Dependent Patient Vitals'},
        ),
        migrations.AlterModelOptions(
            name='patientallergy',
            options={'ordering': ['allergy_name'], 'verbose_name_plural': 'Patient Allergies'},
        ),
        migrations.AlterModelOptions(
            name='patientmedication',
            options={'ordering': ['-prescribed_at'], 'verbose_name_plural': 'Patient Medications'},
        ),
        migrations.AlterModelOptions(
            name='patientvitals',
            options={'ordering': ['-recorded_at'], 'verbose_name_plural': 'Patient Vitals'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdoctoravailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_availabilities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentpatient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentpatientallergy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_allergies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentpatientmedication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_medications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentpatientvitals',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_vitals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorrating',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
