# Generated by Django 6.0 on 2025-12-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_dependentpatientallergy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentpatientmedication',
            options={'ordering': ['-prescribed_at'], 'verbose_name_plural': 'Dependent Patient Medications'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependentappointment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependentappointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
