# Generated by Django 6.0 on 2025-12-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_dependentpatientmedication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentpatientmedication',
            options={'ordering': ['-prescribed_at'], 'verbose_name': 'Dependent Patient Medication', 'verbose_name_plural': 'Dependent Patient Medications'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='dependentappointment',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='dependentappointment',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='is_archived',
        ),
    ]
