# Generated by Django 6.0 on 2025-12-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_appointment_archived_at_appointment_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='dependentappointment',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='dependentappointment',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='dependentpatient',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='dependentpatient',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='dependentpatient',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='is_archived',
        ),
    ]
