# Generated by Django 6.0 on 2025-12-19 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_record', to='website.appointment')),
            ],
        ),
    ]
