# Generated by Django 6.0 on 2025-12-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_completedappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_availabilities', to='website.doctorinfo')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
