# Generated by Django 6.0 on 2025-12-19 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_customdoctoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_str', models.CharField(editable=False, max_length=20)),
                ('reason_for_visit', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dependent_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dependentpatient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.patientinfo')),
            ],
        ),
    ]
