# Generated by Django 6.0 on 2025-12-24 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_appointment_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_appointment_id', models.IntegerField(db_index=True)),
                ('appointment_type', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=301)),
                ('doctor_name', models.CharField(max_length=301)),
                ('doctor_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Appointment',
                'verbose_name_plural': 'Archived Appointments',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedDependentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_patient_id', models.CharField(db_index=True, max_length=20)),
                ('guardian_id', models.IntegerField(blank=True, null=True)),
                ('guardian_username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_dependents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Dependent Patient',
                'verbose_name_plural': 'Archived Dependent Patients',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedDoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_doctor_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_username', models.CharField(max_length=150)),
                ('user_full_name', models.CharField(max_length=301)),
                ('user_email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('was_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Doctor Info',
                'verbose_name_plural': 'Archived Doctor Info',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_record_id', models.IntegerField(db_index=True)),
                ('patient_id_str', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=301)),
                ('reason_for_visit', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('prescriptions', models.JSONField(blank=True, default=list)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Medical Record',
                'verbose_name_plural': 'Archived Medical Records',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedPatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_patient_id', models.CharField(db_index=True, max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_username', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_full_name', models.CharField(max_length=301)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Patient Info',
                'verbose_name_plural': 'Archived Patient Info',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('original_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Record',
                'verbose_name_plural': 'Deleted Records',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
