# Generated by Django 6.0 on 2025-12-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_doctorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
    ]
